# Generated by Django 5.0.3 on 2024-03-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_alter_gender_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
