# Generated by Django 5.0.3 on 2024-03-18 18:24

import users_app.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_remove_user_gender_alter_gender_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users_app.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
