# Generated by Django 5.0.3 on 2024-03-19 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0009_professor_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'استاد', 'verbose_name_plural': 'اساتید'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'دانشجو', 'verbose_name_plural': 'دانشجویان'},
        ),
        migrations.AlterField(
            model_name='professor',
            name='first_name',
            field=models.CharField(max_length=120, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='جنیست'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='شماره استادی'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL, verbose_name='یوزر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=120, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='جنیست'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='شماره دانشجویی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='یوزر'),
        ),
    ]
