# Generated by Django 5.0.3 on 2024-03-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0010_alter_professor_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
