# Generated by Django 5.0.3 on 2024-03-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.BigIntegerField(db_index=True, verbose_name='کد درس')),
                ('course_title', models.CharField(max_length=120, verbose_name='نام درس')),
                ('number_of_unit', models.IntegerField(db_index=True, verbose_name='تعداد واحد')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
            },
        ),
    ]
