# Generated by Django 5.0.3 on 2024-03-23 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentinglesson',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenting_lesson', to='users_app.professor', verbose_name='استاد'),
        ),
        migrations.AddField(
            model_name='lessonpresented',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_presented', to='lessons_app.semester', verbose_name='ترم'),
        ),
        migrations.AddField(
            model_name='takinglesson',
            name='lesson_presented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taking_lesson', to='lessons_app.lessonpresented', verbose_name='درس ارائه شده'),
        ),
        migrations.AddField(
            model_name='takinglesson',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taking_lesson', to='users_app.student', verbose_name='دانشجو'),
        ),
        migrations.AddField(
            model_name='teachingtime',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_time', to='lessons_app.lessonpresented', verbose_name='درس'),
        ),
        migrations.AddField(
            model_name='teachingtime',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_time', to='lessons_app.classroom', verbose_name='کلاس'),
        ),
        migrations.AddField(
            model_name='week',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='lessons_app.semester', verbose_name='ترم'),
        ),
        migrations.AddField(
            model_name='teachingtime',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_time', to='lessons_app.week', verbose_name='هفته'),
        ),
    ]
