# Generated by Django 5.0.3 on 2024-03-23 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons_app', '0002_initial'),
        ('presence_absence_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenceabsence',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_absence', to='users_app.professor', verbose_name='استاد'),
        ),
        migrations.AddField(
            model_name='presenceabsence',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_absence', to='lessons_app.classroom', verbose_name='جلسه'),
        ),
        migrations.AddField(
            model_name='presenceabsence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_absence', to='users_app.student', verbose_name='دانشجو'),
        ),
        migrations.AddField(
            model_name='presenceabsence',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_absence', to='lessons_app.week', verbose_name='هفته'),
        ),
    ]
